# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FizzyMd < Formula
  desc "Transparent Markdown→HTML wrapper for Fizzy CLI"
  homepage "https://github.com/zainfathoni/fizzy-md"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.0/fizzy-md_0.1.0_Darwin_x86_64.tar.gz"
      sha256 "656bc35bb5359ddb841a1096b059576a3ce72723f5574b80887593eeda9b51ad"
    end
    on_arm do
      url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.0/fizzy-md_0.1.0_Darwin_arm64.tar.gz"
      sha256 "617429cb8008e40c1d496401d6054dd350436af56c5a5c980d9e528c7205d6a7"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.0/fizzy-md_0.1.0_Linux_x86_64.tar.gz"
        sha256 "cd5fd493ae3a4390e173632a29778520d619fb9adf315e40b817373093efc5d6"
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.0/fizzy-md_0.1.0_Linux_arm64.tar.gz"
        sha256 "556e159e8dd2932741b2ff3ed2cafc8b9336e5213194a7d32706a8c202780b45"
      end
    end
  end

  def install
    bin.install "fizzy-md"
  end

  test do
    system "#{bin}/fizzy-md", "--version"
  end
end
