# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class FizzyMd < Formula
  desc "Transparent Markdown→HTML wrapper for Fizzy CLI"
  homepage "https://github.com/zainfathoni/fizzy-md"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.2/fizzy-md_0.1.2_Darwin_x86_64.tar.gz"
      sha256 "602c201fc84dbc5674b268a5bd216cb1a59ac2eed689f85bf09daec9c9f88a77"

      def install
        bin.install "fizzy-md"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.2/fizzy-md_0.1.2_Darwin_arm64.tar.gz"
      sha256 "7c49f54211b12f3944d2b27ffea64774b80590ae33c898050bb5728b7718200b"

      def install
        bin.install "fizzy-md"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.2/fizzy-md_0.1.2_Linux_x86_64.tar.gz"
      sha256 "87892647526fd2f968950115bc52492a22015f1ab9883813f6e442bbd1712c29"
      def install
        bin.install "fizzy-md"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zainfathoni/fizzy-md/releases/download/v0.1.2/fizzy-md_0.1.2_Linux_arm64.tar.gz"
      sha256 "59da513c42197f28df373e53f924dd118e3cd6e2cb39f11b10667b5838c0812c"
      def install
        bin.install "fizzy-md"
      end
    end
  end

  test do
    system "#{bin}/fizzy-md --version"
  end
end
